version: '3'
services:
  node-local-0:
    image: centralitycontainerregistry-on.azurecr.io/centrality/cennznet:rimu
    volumes:
      - "./target/node_local_0:/mnt/node"
      - "./genesis/:/mnt/genesis:ro"
    command:
      - --chain=/mnt/genesis/local/local.json
      - --base-path=/mnt/node
      - --name=‼️${HOSTNAME:-ken}-0
      - --pruning=archive
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"

volumes:
  node_ken_0:
