nodePath: ${ODIN_DIST_DIRECTORY}/cennznet-node
logsPrefix: ${ODIN_LOG_DATA_DIRECTORY}
nodeArgs:
#  - --validator
#  - --key=0x0b5660f358b4c54b42ab766d51bafa76d54886e92cbd7773057448dd79f2d91d
  - --pruning=archive
#  - --name
#  - Odin-test
  - --chain
  - ./genesis/local/local.json
