nodePath: ${ODIN_DIST_DIRECTORY}/cennznet-node
logsPrefix: ${ODIN_LOG_DATA_DIRECTORY}
nodeArgs:
#  - --validator
#  - --key=0x8b1f2618b5a41535c4a2304ff742919bd04b1399bc9345c8963c727d399c2266
#  - --key=0xba99a32e2e8e1d1da6aa9ab8b95bed167dac89eca301759c4d5c7fa2878f78ea
#  - --key=0x0b5660f358b4c54b42ab766d51bafa76d54886e92cbd7773057448dd79f2d91d
  - --pruning=archive
#  - --name
#  - Odin-test
  - --chain
  - ./genesis/local/local.json

walletLogging: true
statePath: ${ODIN_USER_DATA_DIRECTORY}/Odin
walletPath: ${ODIN_INSTALL_DIRECTORY}/Frontend
launcherLogsPrefix: ${ODIN_LOG_DATA_DIRECTORY}
walletArgs: []
reportServer: http://localhost:8080
nodeDbPath: ./dist/Odin/DB-1.0
updaterPath: /usr/bin/open
workingDir: ./dist/Odin
frontendOnlyMode: true
nodeLogPath: null
updaterArgs:
  - -FW
configuration:
  seed: null
  filePath: ${ODIN_INSTALL_DIRECTORY}/configuration.yaml
  key: mainnet_wallet_macos64
  systemStart: null
updateArchive: ./dist/Odin/installer.pkg
nodeLogConfig: ${ODIN_INSTALL_DIRECTORY}/log-config-prod.yaml
nodeTimeoutSec: 60
updateWindowsRunner: null
tlsPath: ./dist/Odin/tls
x509ToolPath: ${ODIN_INSTALL_DIRECTORY}/cennznet-x509-certificates
