nodePath: ${APP_DIST_DIRECTORY}/cennznet-node
logsPrefix: ${APP_LOG_DATA_DIRECTORY}
nodeArgs:
  #  - --validator
  #  - --key=0x0b5660f358b4c54b42ab766d51bafa76d54886e92cbd7773057448dd79f2d91d
  #  - -ldebug
  # - -l afg=trace
  # - --pruning=archive
#  - --name
#  - App-test
#  - --chain
#  - ./genesis/local/local.json
