nodePath: ./dist/cennznet-node
logsPrefix: ./dist/Odin/logs
walletLogging: true
nodeArgs:
  - --name
  - ken-test
statePath: ./dist/Odin
walletPath: ${ODIN_INSTALL_DIRECTORY}/Frontend
launcherLogsPrefix: ./dist/Odin/Logs/pub/
walletArgs: []
reportServer: http://localhost:8080
nodeDbPath: ./dist/Odin/DB-1.0
updaterPath: /usr/bin/open
workingDir: ./dist/Odin
frontendOnlyMode: true
nodeLogPath: null
updaterArgs:
  - -FW
configuration:
  seed: null
  filePath: ${ODIN_INSTALL_DIRECTORY}/configuration.yaml
  key: mainnet_wallet_macos64
  systemStart: null
updateArchive: ./dist/Odin/installer.pkg
nodeLogConfig: ${ODIN_INSTALL_DIRECTORY}/log-config-prod.yaml
nodeTimeoutSec: 60
updateWindowsRunner: null
tlsPath: ./dist/Odin/tls
x509ToolPath: ${ODIN_INSTALL_DIRECTORY}/cennznet-x509-certificates
