version: 2
jobs:
  build:
    working_directory: ~/runanode
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          name: Restore package cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install --frozen-lockfile
      - save_cache:
          name: Save package cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run jest
          command: npm run jest

workflows:
  version: 2
  PR build:
    jobs:
      - build
