// flow-typed signature: 8a996de676eafdf4f794ff53ae665873
// flow-typed version: <<STUB>>/@polkadot/api_v^0.37.4/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polkadot/api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polkadot/api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polkadot/api/Base' {
  declare module.exports: any;
}

declare module '@polkadot/api/promise/Combinator' {
  declare module.exports: any;
}

declare module '@polkadot/api/promise/Combinators.spec' {
  declare module.exports: any;
}

declare module '@polkadot/api/promise/index' {
  declare module.exports: any;
}

declare module '@polkadot/api/promise/SubmittableExtrinsic' {
  declare module.exports: any;
}

declare module '@polkadot/api/promise/SubmittableExtrinsic.spec' {
  declare module.exports: any;
}

declare module '@polkadot/api/promise/types' {
  declare module.exports: any;
}

declare module '@polkadot/api/rx/index' {
  declare module.exports: any;
}

declare module '@polkadot/api/rx/SubmittableExtrinsic' {
  declare module.exports: any;
}

declare module '@polkadot/api/rx/types' {
  declare module.exports: any;
}

declare module '@polkadot/api/types' {
  declare module.exports: any;
}

declare module '@polkadot/api/util/filterEvents' {
  declare module.exports: any;
}

declare module '@polkadot/api/util/logging' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polkadot/api/Base.js' {
  declare module.exports: $Exports<'@polkadot/api/Base'>;
}
declare module '@polkadot/api/index' {
  declare module.exports: $Exports<'@polkadot/api'>;
}
declare module '@polkadot/api/index.js' {
  declare module.exports: $Exports<'@polkadot/api'>;
}
declare module '@polkadot/api/promise/Combinator.js' {
  declare module.exports: $Exports<'@polkadot/api/promise/Combinator'>;
}
declare module '@polkadot/api/promise/Combinators.spec.js' {
  declare module.exports: $Exports<'@polkadot/api/promise/Combinators.spec'>;
}
declare module '@polkadot/api/promise/index.js' {
  declare module.exports: $Exports<'@polkadot/api/promise/index'>;
}
declare module '@polkadot/api/promise/SubmittableExtrinsic.js' {
  declare module.exports: $Exports<'@polkadot/api/promise/SubmittableExtrinsic'>;
}
declare module '@polkadot/api/promise/SubmittableExtrinsic.spec.js' {
  declare module.exports: $Exports<'@polkadot/api/promise/SubmittableExtrinsic.spec'>;
}
declare module '@polkadot/api/promise/types.js' {
  declare module.exports: $Exports<'@polkadot/api/promise/types'>;
}
declare module '@polkadot/api/rx/index.js' {
  declare module.exports: $Exports<'@polkadot/api/rx/index'>;
}
declare module '@polkadot/api/rx/SubmittableExtrinsic.js' {
  declare module.exports: $Exports<'@polkadot/api/rx/SubmittableExtrinsic'>;
}
declare module '@polkadot/api/rx/types.js' {
  declare module.exports: $Exports<'@polkadot/api/rx/types'>;
}
declare module '@polkadot/api/types.js' {
  declare module.exports: $Exports<'@polkadot/api/types'>;
}
declare module '@polkadot/api/util/filterEvents.js' {
  declare module.exports: $Exports<'@polkadot/api/util/filterEvents'>;
}
declare module '@polkadot/api/util/logging.js' {
  declare module.exports: $Exports<'@polkadot/api/util/logging'>;
}
