// flow-typed signature: 36e2376b34092306269013a62ea7b5bd
// flow-typed version: <<STUB>>/@polkadot/rpc-provider_v^0.37.4/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polkadot/rpc-provider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polkadot/rpc-provider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polkadot/rpc-provider/coder/decodeResponse.spec' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/coder/encodeJson.spec' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/coder/encodeObject.spec' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/coder/index' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/defaults' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/http/index' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/http/polyfill' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/http/types' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/mock/index' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/mock/on.spec' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/mock/send.spec' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/mock/subscribe.spec' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/mock/types' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/mock/unsubscribe.spec' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/types' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/ws/index' {
  declare module.exports: any;
}

declare module '@polkadot/rpc-provider/ws/polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polkadot/rpc-provider/coder/decodeResponse.spec.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/coder/decodeResponse.spec'>;
}
declare module '@polkadot/rpc-provider/coder/encodeJson.spec.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/coder/encodeJson.spec'>;
}
declare module '@polkadot/rpc-provider/coder/encodeObject.spec.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/coder/encodeObject.spec'>;
}
declare module '@polkadot/rpc-provider/coder/index.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/coder/index'>;
}
declare module '@polkadot/rpc-provider/defaults.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/defaults'>;
}
declare module '@polkadot/rpc-provider/http/index.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/http/index'>;
}
declare module '@polkadot/rpc-provider/http/polyfill.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/http/polyfill'>;
}
declare module '@polkadot/rpc-provider/http/types.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/http/types'>;
}
declare module '@polkadot/rpc-provider/index' {
  declare module.exports: $Exports<'@polkadot/rpc-provider'>;
}
declare module '@polkadot/rpc-provider/index.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider'>;
}
declare module '@polkadot/rpc-provider/mock/index.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/mock/index'>;
}
declare module '@polkadot/rpc-provider/mock/on.spec.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/mock/on.spec'>;
}
declare module '@polkadot/rpc-provider/mock/send.spec.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/mock/send.spec'>;
}
declare module '@polkadot/rpc-provider/mock/subscribe.spec.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/mock/subscribe.spec'>;
}
declare module '@polkadot/rpc-provider/mock/types.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/mock/types'>;
}
declare module '@polkadot/rpc-provider/mock/unsubscribe.spec.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/mock/unsubscribe.spec'>;
}
declare module '@polkadot/rpc-provider/types.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/types'>;
}
declare module '@polkadot/rpc-provider/ws/index.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/ws/index'>;
}
declare module '@polkadot/rpc-provider/ws/polyfill.js' {
  declare module.exports: $Exports<'@polkadot/rpc-provider/ws/polyfill'>;
}
